# Generated by Django 3.1.5 on 2021-02-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanbai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafield',
            name='field_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extrafield',
            name='value_type',
            field=models.IntegerField(choices=[('1', 'String'), ('2', 'Integer')], default='1'),
        ),
    ]
