# Generated by Django 3.1.5 on 2021-01-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanbai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_edited',
            field=models.DateTimeField(null=True),
        ),
    ]
