# Generated by Django 3.1.5 on 2021-02-02 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanbai', '0003_vehicleinfo_engine_displacement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previousvehicleinfo',
            old_name='model_specificaiton',
            new_name='model_specification',
        ),
    ]
