# Generated by Django 3.1.5 on 2021-04-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanbai', '0003_auto_20210328_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemization',
            name='previous_vehicle_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='下取車価額'),
        ),
    ]
