# Generated by Django 3.1.5 on 2021-04-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanbai', '0004_itemization_previous_vehicle_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemization',
            name='previous_vehicle_price',
        ),
    ]
