# Generated by Django 3.1.5 on 2021-02-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanbai', '0004_auto_20210202_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancetax',
            name='income_tax',
        ),
        migrations.AddField(
            model_name='insurancetax',
            name='acquisition_tax',
            field=models.PositiveIntegerField(null=True, verbose_name='得得税'),
        ),
    ]
