# Generated by Django 3.1.5 on 2021-02-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanbai', '0005_auto_20210204_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancetax',
            name='weight_tax',
            field=models.PositiveIntegerField(null=True, verbose_name='重量税'),
        ),
    ]
