# Generated by Django 3.1.5 on 2021-02-04 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanbai', '0006_insurancetax_weight_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumptiontax',
            old_name='remiaining_liability',
            new_name='remaining_liability',
        ),
    ]
