# Generated by Django 3.1.5 on 2021-02-05 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hanbai', '0007_auto_20210204_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsection',
            name='fields',
        ),
        migrations.AddField(
            model_name='extrafield',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='hanbai.customsection'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomSectionFields',
        ),
    ]
